declare module 'tributejs/src/Tribute.js'
declare module 'markdown-it-emoji/light'
declare module 'markdown-it-for-inline';
declare module 'emoji-short-name';
declare module 'toastify-js';
declare module '@theme-ui/color';
declare module '@theme-ui/presets';
declare module 'types/lodash.isequal';
declare module 'lodash.isequal';
declare module 'emoji-mart';
declare module 'match-sorter';